# Generated by Django 4.2.3 on 2023-07-24 14:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoSpace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("cisco_id", models.CharField(max_length=128)),
                ("call_id", models.CharField(max_length=128)),
                ("secret", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "owner_call_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_owner_ask_for_secret", models.BooleanField(default=False)),
                (
                    "owner_secret",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "guest_call_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_guest_ask_for_secret", models.BooleanField(default=False)),
                (
                    "guest_secret",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("owner_jid", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "verbose_name": "Cisco Room",
                "verbose_name_plural": "Cisco Rooms",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("cisco_id", models.CharField(max_length=128)),
                ("user_jid", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("email", models.CharField(max_length=128)),
                (
                    "user_profile",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("username", models.CharField(max_length=128)),
                ("password", models.CharField(max_length=128)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
