# Generated by Django 4.2.4 on 2023-08-09 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ciscomeetingserver", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoSpaceRoles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("cospace_cisco_id", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("administrator", "Administrator"),
                            ("owner", "Owner"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="User",
            new_name="CiscoUser",
        ),
        migrations.DeleteModel(
            name="ApiCredential",
        ),
        migrations.AddConstraint(
            model_name="cospaceroles",
            constraint=models.UniqueConstraint(
                fields=("user", "cospace_cisco_id"), name="unique CoSpace Role"
            ),
        ),
    ]
